### PR TITLE
add archived centos repositories

### PR DESCRIPTION
**Pull request by msherman64**
This swaps in archived centos8 repos to make the build work again.
TODO: verify which images still fail to build
TODO: evaluate the added repos with centos stream8 base image

### CODE REVIEW

**Comment by priteau** [comment]
I am curious why you are using this site instead of `vault.centos.org`?

**Comment by msherman64** [comment]
Mostly that it's faster, vault.centos.org was frequently timing out.

**Comment by priteau** [comment]
Good to know!

**Comment by msherman64** [comment]
Closing this PR, upstream has added initial support for centos8 stream in this commit: https://github.com/openstack/kolla/commit/76841d99ec35dccf7231ef67938aaf3629957a6e

**Pull request closed without merging**
